name: Build PDF
on:
  push:
    branches:
      - main

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 17
      - run: mkdir -p dist
      - run: npm install md-to-pdf
      - run: node build/build.js
      - uses: actions/upload-artifact@v1
        with:
          name: book.md
          path: dist/book.md
      - uses: actions/upload-artifact@v1
        with:
          name: book.pdf
          path: dist/book.pdf    
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            dist/book.pdf
            dist/book.md
